# -*- coding: utf-8 -*-
"""spib_scraper (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y4fDD26zAut8vldOcpQD6WdFU_xMvyD5

# SPIB Scraper (English + French)

**Last updated:** 2026-03-10

Scrapes the SPIB entries (EN + FR), normalizes bilingual fields, aligns bank prefixes across languages (e.g., **PSE ↔ POE**, **PSU ↔ POU**), preserves embedded links, merges EN/FR rows, and exports CSV/Excel.

**Sources**
- EN: https://www.canada.ca/en/treasury-board-secretariat/services/access-information-privacy/access-information/info-source/standard-personal-information-banks.html
- FR: https://www.canada.ca/fr/secretariat-conseil-tresor/services/acces-information-protection-reseignements-personnels/acces-information/info-source/fichiers-renseignements-personnels-ordinaires.html
"""



import re
import requests
import pandas as pd
from bs4 import BeautifulSoup, Tag
from urllib.parse import urljoin
from unidecode import unidecode
pd.set_option('display.max_colwidth', 200)

URL_EN = 'https://www.canada.ca/en/treasury-board-secretariat/services/access-information-privacy/access-information/info-source/standard-personal-information-banks.html'
URL_FR = 'https://www.canada.ca/fr/secretariat-conseil-tresor/services/acces-information-protection-reseignements-personnels/acces-information/info-source/fichiers-renseignements-personnels-ordinaires.html'
CSV_PATH = 'spib_en_fr.csv'
XLSX_PATH = 'spib_en_fr.xlsx'
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (compatible; SPIB-Scraper/1.1; +https://example.local)'
}

# Annex B code families (EN/FR) used to normalize bilingual bank prefixes.
PREFIX_MAP_TO_EN = {
    'POE': 'PSE',  # FR employee standard -> EN employee standard
    'POU': 'PSU',  # FR public standard -> EN public standard
    'PSE': 'PSE',
    'PSU': 'PSU',
}

MONTH_MAP = {
    'january': 1, 'janvier': 1,
    'february': 2, 'fevrier': 2,
    'march': 3, 'mars': 3,
    'april': 4, 'avril': 4,
    'may': 5, 'mai': 5,
    'june': 6, 'juin': 6,
    'july': 7, 'juillet': 7,
    'august': 8, 'aout': 8,
    'september': 9, 'septembre': 9,
    'october': 10, 'octobre': 10,
    'november': 11, 'novembre': 11,
    'december': 12, 'decembre': 12,
}
MONTH_NAME_RE = r'(?:' + '|'.join(sorted(MONTH_MAP.keys(), key=len, reverse=True)) + r')'

UPDATE_DATE_CUE = (
    r'(?:last\s+updated|updated|terminated|'
    r'derniere\s+mise\s+a\s+jour(?:\s+de\s+la\s+description)?|'
    r'mis\s+a\s+jour|mise\s+a\s+jour|supprimee?)'
)

RECORD_CODE_RE = re.compile(r'\b(PRN|NDP)\s*([0-9]{3,4}[A-Z]?)\b', flags=re.I)

def fetch_soup(url: str) -> BeautifulSoup:
    r = requests.get(url, headers=HEADERS, timeout=60)
    r.raise_for_status()
    return BeautifulSoup(r.text, 'lxml')

# Canonical keys for output
CANONICAL_KEYS = [
    'description',
    'note',
    'class_of_individuals',
    'purpose',
    'consistent_uses',
    'retention_disposal',
    'rda_number',
    'related_record_number',
    'bank_number',
]

# Label map (ASCII-normalized prefixes)
LABEL_MAP = {
    # English
    'description': 'description',
    'note': 'note',
    'class of individuals': 'class_of_individuals',
    'purpose': 'purpose',
    'consistent uses': 'consistent_uses',
    'retention and disposal standards': 'retention_disposal',
    'rda number': 'rda_number',
    'related record number': 'related_record_number',
    'bank number': 'bank_number',
    # French
    'description': 'description',
    'remarque': 'note',
    'note': 'note',
    'categorie de personnes': 'class_of_individuals',
    'objet': 'purpose',
    'but': 'purpose',
    'usages compatibles': 'consistent_uses',
    'normes de conservation': 'retention_disposal',
    # User-specified exact FR labels
    'numero add': 'rda_number',                        # Numéro ADD
    'numero de renvoi au document': 'related_record_number',  # Numéro de renvoi au document
    # Older/other variants (kept for robustness)
    'numero d autorisation de disposition': 'rda_number',
    'numero de dossier connexe': 'related_record_number',
    'numero de fichier': 'bank_number',
}

def clean_label(text: str) -> str:
    t = unidecode((text or '').strip().lower())
    t = t.replace('\xa0', ' ')
    t = t.replace("'", ' ')
    t = t.rstrip(':')
    t = re.sub(r'\s+', ' ', t).strip()
    return t

def label_to_key(label_text: str):
    cl = clean_label(label_text)
    if cl in LABEL_MAP:
        return LABEL_MAP[cl]
    for k in LABEL_MAP:
        if cl.startswith(k):
            return LABEL_MAP[k]
    return None

def iter_entry_sections(soup: BeautifulSoup, base_url: str):
    entries = []
    for h3 in soup.find_all('h3'):
        if not h3.has_attr('id'):
            continue
        entry_id = h3['id'].strip()
        entry_title = h3.get_text(' ', strip=True)
        fragment = f'#{entry_id}'
        fields_raw, fields_links = {}, {}
        sib = h3.next_sibling
        while sib:
            if isinstance(sib, Tag) and sib.name == 'h3':
                break
            if isinstance(sib, Tag) and sib.name == 'p':
                strong = sib.find('strong')
                if strong:
                    raw_label = strong.get_text(' ', strip=True)
                    sib_clone = BeautifulSoup(str(sib), 'lxml')
                    st = sib_clone.find('strong')
                    if st: st.extract()
                    value_text = sib_clone.get_text(' ', strip=True)
                    value_text = value_text.lstrip(':').strip()
                    fields_raw[raw_label] = value_text
                    links = []
                    for a in sib.find_all('a', href=True):
                        txt = a.get_text(' ', strip=True)
                        href = urljoin(base_url, a['href'])
                        links.append((txt, href))
                    if links:
                        fields_links[raw_label] = links
            sib = sib.next_sibling
        entries.append({
            'entry_id': entry_id,
            'entry_title': entry_title,
            'fragment': fragment,
            'fields_raw': fields_raw,
            'fields_links': fields_links,
        })
    return entries

def normalize_bank_number(value: str):
    if not isinstance(value, str):
        return None
    m = re.search(r"\b([A-Z]{2,4})\s*-?\s*(\d{3,4}[A-Z]?)\b", value.upper())
    if not m:
        return None
    prefix, num = m.group(1), m.group(2)
    norm_prefix = PREFIX_MAP_TO_EN.get(prefix, prefix)
    return f"{norm_prefix} {num}"

def bank_from_id(idv: str):
    if not isinstance(idv, str):
        return None
    m = re.search(r'([a-z]{2,4})\s*0*(\d{3,4}[a-z]?)', idv, flags=re.I)
    if not m:
        return None
    prefix, num = m.group(1).upper(), m.group(2).upper()
    norm_prefix = PREFIX_MAP_TO_EN.get(prefix, prefix)
    return f"{norm_prefix} {num}"

def related_numbers_set(value: str):
    if not isinstance(value, str):
        return set()
    # Keep only explicit PRN/NDP references and ignore URL fragments.
    return {code.upper() for _, code in RECORD_CODE_RE.findall(value)}

def related_numbers_key(value: str):
    nums = related_numbers_set(value)
    return ','.join(sorted(nums)) if nums else None

def normalize_related_record_numbers(value: str):
    if not isinstance(value, str):
        return None
    seen = []
    for prefix, num in RECORD_CODE_RE.findall(value):
        code = f"{prefix.upper()} {num.upper()}"
        if code not in seen:
            seen.append(code)
    return ', '.join(seen) if seen else None

def build_iso_date(year: int, month: int, day: int = 1):
    try:
        dt = pd.Timestamp(year=int(year), month=int(month), day=int(day))
        return dt.strftime('%Y-%m-%d')
    except Exception:
        return None

def parse_last_modified_from_note(note: str):
    if not isinstance(note, str):
        return None
    text = note.split('  |  Links: ')[0]
    text_norm = unidecode(text.replace('\xa0', ' ')).lower().strip()
    if not text_norm:
        return None

    patterns = [
        rf'{UPDATE_DATE_CUE}\D{{0,40}}?(\d{{4}})[/-](\d{{1,2}})[/-](\d{{1,2}})',
        rf'{UPDATE_DATE_CUE}\D{{0,40}}?(?:in\s+|en\s+)?\b({MONTH_NAME_RE})\b\s+(\d{{1,2}}),?\s+(\d{{4}})',
        rf'{UPDATE_DATE_CUE}\D{{0,40}}?(?:in\s+|en\s+)?(\d{{1,2}})\s+\b({MONTH_NAME_RE})\b\s+(\d{{4}})',
        rf'{UPDATE_DATE_CUE}\D{{0,40}}?(?:in\s+|en\s+)?\b({MONTH_NAME_RE})\b\s+(\d{{4}})',
    ]

    m = re.search(patterns[0], text_norm, flags=re.I)
    if m:
        return build_iso_date(int(m.group(1)), int(m.group(2)), int(m.group(3)))

    m = re.search(patterns[1], text_norm, flags=re.I)
    if m:
        month = MONTH_MAP.get(m.group(1))
        if month:
            return build_iso_date(int(m.group(3)), month, int(m.group(2)))

    m = re.search(patterns[2], text_norm, flags=re.I)
    if m:
        month = MONTH_MAP.get(m.group(2))
        if month:
            return build_iso_date(int(m.group(3)), month, int(m.group(1)))

    m = re.search(patterns[3], text_norm, flags=re.I)
    if m:
        month = MONTH_MAP.get(m.group(1))
        if month:
            return build_iso_date(int(m.group(2)), month, 1)

    return None

def derive_last_modified(note_en: str, note_fr: str):
    return parse_last_modified_from_note(note_en) or parse_last_modified_from_note(note_fr)

def normalize_entries(entries: list, base_url: str, lang: str) -> pd.DataFrame:
    rows = []
    for e in entries:
        record = {k: None for k in CANONICAL_KEYS}
        record['entry_id'] = e['entry_id']
        record['entry_title'] = e['entry_title']
        record['source_url'] = base_url + e['fragment']
        record['lang'] = lang
        for raw_label, value in e['fields_raw'].items():
            key = label_to_key(raw_label)
            if key:
                record[key] = value
        for raw_label, links in e.get('fields_links', {}).items():
            key = label_to_key(raw_label)
            if key:
                md_links = [f"{txt} ({href})" for (txt, href) in links]
                link_str = '; '.join(md_links)
                record[key] = (record.get(key) + '  |  Links: ' if record.get(key) else '') + f"{link_str}"
        record['bank_number_clean'] = normalize_bank_number(record.get('bank_number'))
        rows.append(record)
    df = pd.DataFrame(rows)
    df['bank_number_from_id'] = df['entry_id'].apply(bank_from_id)
    df['_merge_key'] = df['bank_number_clean'].fillna(df['bank_number_from_id'])
    df['_related_numbers'] = df['related_record_number'].apply(related_numbers_set)
    df['_related_key'] = df['related_record_number'].apply(related_numbers_key)
    return df

def should_reject_bank_match(en_row, fr_row) -> bool:
    en_rel = en_row.get('_related_numbers') or set()
    fr_rel = fr_row.get('_related_numbers') or set()
    return bool(en_rel and fr_rel and en_rel.isdisjoint(fr_rel))

def pair_entries(df_en: pd.DataFrame, df_fr: pd.DataFrame) -> pd.DataFrame:
    paired_en = set()
    paired_fr = set()
    pairs = []

    def add_pair(en_idx, fr_idx, method: str):
        paired_en.add(en_idx)
        paired_fr.add(fr_idx)
        pairs.append((en_idx, fr_idx, method))

    # Pass 1: exact ID matches (e.g., "categories").
    shared_ids = sorted(set(df_en['entry_id']).intersection(set(df_fr['entry_id'])))
    for entry_id in shared_ids:
        en_idx = df_en.index[df_en['entry_id'] == entry_id].tolist()
        fr_idx = df_fr.index[df_fr['entry_id'] == entry_id].tolist()
        if len(en_idx) == 1 and len(fr_idx) == 1:
            add_pair(en_idx[0], fr_idx[0], 'entry_id')

    # Pass 2: bank-number key matches, but reject contradictory related-record pairs.
    en_unmatched = [i for i in df_en.index if i not in paired_en]
    fr_unmatched = [i for i in df_fr.index if i not in paired_fr]
    en_by_key = {}
    fr_by_key = {}
    for i in en_unmatched:
        key = df_en.at[i, '_merge_key']
        if pd.notna(key):
            en_by_key.setdefault(key, []).append(i)
    for j in fr_unmatched:
        key = df_fr.at[j, '_merge_key']
        if pd.notna(key):
            fr_by_key.setdefault(key, []).append(j)
    for key in sorted(set(en_by_key).intersection(set(fr_by_key))):
        if len(en_by_key[key]) == 1 and len(fr_by_key[key]) == 1:
            i = en_by_key[key][0]
            j = fr_by_key[key][0]
            if should_reject_bank_match(df_en.loc[i], df_fr.loc[j]):
                continue
            add_pair(i, j, 'bank_key')

    # Pass 3: use Related record number (PRN/NDP numeric IDs) as fallback bridge.
    en_unmatched = [i for i in df_en.index if i not in paired_en]
    fr_unmatched = [j for j in df_fr.index if j not in paired_fr]
    en_by_related = {}
    fr_by_related = {}
    for i in en_unmatched:
        key = df_en.at[i, '_related_key']
        if pd.notna(key):
            en_by_related.setdefault(key, []).append(i)
    for j in fr_unmatched:
        key = df_fr.at[j, '_related_key']
        if pd.notna(key):
            fr_by_related.setdefault(key, []).append(j)
    for key in sorted(set(en_by_related).intersection(set(fr_by_related))):
        if len(en_by_related[key]) == 1 and len(fr_by_related[key]) == 1:
            add_pair(en_by_related[key][0], fr_by_related[key][0], 'related_record')

    # Build merged rows in EN order, then remaining FR-only rows.
    pairs_by_en = {en_idx: (fr_idx, method) for en_idx, fr_idx, method in pairs}
    rows = []
    for en_idx in df_en.index:
        if en_idx in pairs_by_en:
            fr_idx, method = pairs_by_en[en_idx]
            en_row = df_en.loc[en_idx]
            fr_row = df_fr.loc[fr_idx]
            row = {f'{c}_en': en_row[c] for c in df_en.columns}
            row.update({f'{c}_fr': fr_row[c] for c in df_fr.columns})
            merge_key = en_row['_merge_key'] if pd.notna(en_row['_merge_key']) else fr_row['_merge_key']
            row['_merge_key'] = merge_key if pd.notna(merge_key) else (en_row['entry_id'] or fr_row['entry_id'])
            row['_match_method'] = method
            rows.append(row)
        elif en_idx not in paired_en:
            en_row = df_en.loc[en_idx]
            row = {f'{c}_en': en_row[c] for c in df_en.columns}
            row['_merge_key'] = en_row['_merge_key'] if pd.notna(en_row['_merge_key']) else en_row['entry_id']
            row['_match_method'] = 'en_only'
            rows.append(row)

    for fr_idx in df_fr.index:
        if fr_idx not in paired_fr:
            fr_row = df_fr.loc[fr_idx]
            row = {f'{c}_fr': fr_row[c] for c in df_fr.columns}
            row['_merge_key'] = fr_row['_merge_key'] if pd.notna(fr_row['_merge_key']) else fr_row['entry_id']
            row['_match_method'] = 'fr_only'
            rows.append(row)

    return pd.DataFrame(rows)

soup_en = fetch_soup(URL_EN)
entries_en = iter_entry_sections(soup_en, URL_EN)
df_en = normalize_entries(entries_en, URL_EN, lang='en')

soup_fr = fetch_soup(URL_FR)
entries_fr = iter_entry_sections(soup_fr, URL_FR)
df_fr = normalize_entries(entries_fr, URL_FR, lang='fr')

print(f'Found EN entries: {len(df_en)}')
print(f'Found FR entries: {len(df_fr)}')
df_en.head(3)
df_fr.head(3)

df_merged = pair_entries(df_en, df_fr)

final_cols_map = [
    ('description_en', 'description_en'),
    ('description_fr', 'description_fr'),
    ('note_en', 'note_en'),
    ('note_fr', 'note_fr'),
    ('class_of_individuals_en', 'class_of_individuals_en'),
    ('class_of_individuals_fr', 'class_of_individuals_fr'),
    ('purpose_en', 'purpose_en'),
    ('purpose_fr', 'purpose_fr'),
    ('consistent_uses_en', 'consistent_uses_en'),
    ('consistent_uses_fr', 'consistent_uses_fr'),
    ('retention_disposal_en', 'retention_disposal_en'),
    ('retention_disposal_fr', 'retention_disposal_fr'),
    ('rda_number_en', 'rda_number_en'),
    ('rda_number_fr', 'rda_number_fr'),
    ('related_record_number_en', 'related_record_number_en'),
    ('related_record_number_fr', 'related_record_number_fr'),
    ('bank_number_en', 'bank_number_en'),
    ('bank_number_fr', 'bank_number_fr'),
    ('entry_id_en', 'entry_id_en'),
    ('entry_id_fr', 'entry_id_fr'),
    ('entry_title_en', 'entry_title_en'),
    ('entry_title_fr', 'entry_title_fr'),
    ('source_url_en', 'url_en'),
    ('source_url_fr', 'url_fr'),
]

out = pd.DataFrame()
out['bank_number_key'] = df_merged['_merge_key']
for src, dst in final_cols_map:
    out[dst] = df_merged.get(src)

out['related_record_number_en'] = out['related_record_number_en'].apply(normalize_related_record_numbers)
out['related_record_number_fr'] = out['related_record_number_fr'].apply(normalize_related_record_numbers)
out['date_last_modified'] = out.apply(
    lambda r: derive_last_modified(r.get('note_en'), r.get('note_fr')),
    axis=1,
)

preferred_order = [
    'bank_number_key',
    'bank_number_en', 'bank_number_fr',
    'entry_id_en', 'entry_id_fr',
    'entry_title_en', 'entry_title_fr',
    'description_en', 'description_fr',
    'note_en', 'note_fr',
    'date_last_modified',
    'class_of_individuals_en', 'class_of_individuals_fr',
    'purpose_en', 'purpose_fr',
    'consistent_uses_en', 'consistent_uses_fr',
    'retention_disposal_en', 'retention_disposal_fr',
    'rda_number_en', 'rda_number_fr',
    'related_record_number_en', 'related_record_number_fr',
    'url_en', 'url_fr'
]
out = out[preferred_order]


out.to_csv(CSV_PATH, index=False)
out.to_excel(XLSX_PATH, index=False, engine='openpyxl')
print(f'Saved CSV -> {CSV_PATH}')
print(f'Saved Excel -> {XLSX_PATH}')

print('Rows in output:', len(out))
print('Rows missing EN:', out['description_en'].isna().sum())
print('Rows missing FR:', out['description_fr'].isna().sum())
print('Match methods:')
print(df_merged['_match_method'].value_counts(dropna=False).to_string())
